---
title: niranjanb.github.go
timezone: America/New_York
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
permalink: "/blog/:title"
name: Niranjan's Blog
description: A blog on Jekyll and GitHub Pages
google_verification: 
include:
- ".htaccess"
exclude:
- README.md
- LICENSE
sass:
  style: compressed
  sass_dir: _sass
markdown: kramdown
kramdown:
  input: GFM
  parse_block_html: true
  hard_wrap: false
highlighter: rouge
